# Generated by Django 5.2.14 on 2026-06-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_content_post_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='memo',
            new_name='content',
        ),
    ]
